package com.example.gyme.feature.members.add

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.example.gyme.domain.model.*
import com.example.gyme.domain.usecase.AddMemberUseCase
import com.example.gyme.domain.usecase.GetMembershipPlansUseCase
import kotlinx.coroutines.flow.*
import kotlinx.coroutines.launch
import java.util.Date

data class AddMemberUiState(
    val isLoading: Boolean = false,
    val name: String = "",
    val phone: String = "",
    val gender: Gender = Gender.MALE,
    val subscriptionStart: Date = Date(),
    val subscriptionEnd: Date? = null,
    val selectedPlan: MembershipPlan? = null,
    val availablePlans: List<MembershipPlan> = emptyList(),
    val discount: String = "0",
    val discountType: DiscountType = DiscountType.PERCENTAGE,
    val isPaid: Boolean = false,
    val error: String? = null,
    val isSuccess: Boolean = false,
    val memberId: String = ""
)

class AddMemberViewModel(
    private val addMemberUseCase: AddMemberUseCase,
    private val getMembershipPlansUseCase: GetMembershipPlansUseCase
) : ViewModel() {

    private val _uiState = MutableStateFlow(AddMemberUiState())
    val uiState: StateFlow<AddMemberUiState> = _uiState.asStateFlow()

    init {
        loadPlans()
    }

    private fun loadPlans() {
        viewModelScope.launch {
            getMembershipPlansUseCase().collect { plans ->
                _uiState.update { it.copy(availablePlans = plans, selectedPlan = plans.firstOrNull()) }
            }
        }
    }

    fun onFullNameChange(name: String) = _uiState.update { it.copy(name = name) }
    fun onPhoneNumberChange(phone: String) = _uiState.update { it.copy(phone = phone) }
    fun onGenderChange(gender: Gender) = _uiState.update { it.copy(gender = gender) }
    fun onPlanChange(plan: MembershipPlan) = _uiState.update { it.copy(selectedPlan = plan) }
    fun onDiscountChange(discount: String) = _uiState.update { it.copy(discount = discount) }
    fun onDiscountTypeChange(type: DiscountType) = _uiState.update { it.copy(discountType = type) }
    fun onSubscriptionStartChange(date: Date) = _uiState.update { it.copy(subscriptionStart = date) }
    fun onSubscriptionEndChange(date: Date?) = _uiState.update { it.copy(subscriptionEnd = date) }

    fun addMember() {
        val state = _uiState.value
        if (state.selectedPlan == null) return

        viewModelScope.launch {
            _uiState.update { it.copy(isLoading = true, error = null) }
            
            val member = Member(
                id = "", // Will be generated by repository or backend
                name = state.name,
                phone = state.phone,
                gender = state.gender,
                subscriptionStart = state.subscriptionStart,
                subscriptionEnd = state.subscriptionEnd,
                planId = state.selectedPlan.id,
                status = MemberStatus.ACTIVE,
                discount = state.discount.toDoubleOrNull() ?: 0.0,
                discountType = state.discountType
            )

            addMemberUseCase(member).onSuccess {
                _uiState.update { it.copy(isLoading = false, isSuccess = true) }
            }.onFailure { e ->
                _uiState.update { it.copy(isLoading = false, error = e.message) }
            }
        }
    }
}
